name: futures_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.4
  - statsmodels=0.14.4
  - scikit-learn=1.5.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=6.0.1
  - jupyter=1.0.0
  - ipython=8.15.0
  - jupyterlab=4.3.4
  - openpyxl=3.1.5
  - xlrd=2.0.1
  - pyyaml=6.0.2
  - joblib=1.4.2
  - pip=25.1
  - linearmodels=6.1
  - pip:
    - arch==7.2.0
    - pandas-datareader==0.10.0
    - pyarrow==20.0.0
    - dask==2024.8.0
    - tqdm==4.67.1
    - tabulate>=0.8.9
    - python-dotenv>=0.19.0
    - lxml==5.4.0
    - cloudpickle==3.1.1
    - fsspec==2025.3.2
